# Generated by Django 2.1.2 on 2018-11-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_auto_20181124_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
