# Generated by Django 2.1.2 on 2018-11-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
