# Generated by Django 2.1.2 on 2018-11-25 09:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_auto_20181125_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='time',
            field=models.TimeField(default=datetime.datetime(2018, 11, 25, 9, 27, 35, 847980, tzinfo=utc)),
        ),
    ]
