# Generated by Django 2.1.2 on 2018-11-25 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0006_auto_20181125_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='time',
            field=models.TimeField(default=datetime.datetime(2018, 11, 25, 9, 43, 31, 226625, tzinfo=utc)),
        ),
    ]
