# Generated by Django 2.1.2 on 2018-11-25 10:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0008_auto_20181125_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.AlterField(
            model_name='employee',
            name='time',
            field=models.TimeField(default=datetime.datetime(2018, 11, 25, 10, 2, 39, 265289, tzinfo=utc)),
        ),
    ]
