# Generated by Django 2.1.2 on 2018-12-06 21:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0010_auto_20181125_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='time',
            field=models.TimeField(default=datetime.datetime(2018, 12, 6, 21, 21, 15, 29898, tzinfo=utc)),
        ),
    ]
