# Generated by Django 2.1.2 on 2018-12-07 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0011_auto_20181206_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='time',
            field=models.TimeField(default=datetime.datetime(2018, 12, 7, 14, 31, 56, 982036, tzinfo=utc)),
        ),
    ]
