# Generated by Django 2.1.2 on 2018-12-08 18:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0012_auto_20181207_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='time',
            field=models.TimeField(default=datetime.datetime(2018, 12, 8, 18, 47, 26, 23378, tzinfo=utc)),
        ),
    ]
