# Generated by Django 2.1.3 on 2018-12-09 11:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0015_auto_20181209_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='time',
            field=models.TimeField(default=datetime.datetime(2018, 12, 9, 11, 8, 24, 851521, tzinfo=utc)),
        ),
    ]
