# Generated by Django 2.1.2 on 2018-10-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_price', models.IntegerField()),
                ('breakfast_only_price', models.IntegerField()),
                ('half_board_price', models.IntegerField()),
                ('full_board_price', models.IntegerField()),
                ('all_inclusive_price', models.IntegerField()),
                ('room_view', models.IntegerField()),
                ('room_type', models.IntegerField()),
                ('is_refundable', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_adult', models.CharField(max_length=2)),
                ('occupation_children', models.CharField(max_length=2)),
                ('room_type', models.CharField(max_length=15)),
                ('room_view', models.CharField(max_length=10)),
                ('room_size', models.CharField(max_length=2)),
                ('room_beds', models.IntegerField()),
                ('room_date_booked', models.ManyToManyField(to='ownerAdmin.Date')),
            ],
        ),
    ]
