# Generated by Django 2.1.2 on 2018-10-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='month',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
