# Generated by Django 2.1.2 on 2018-10-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0003_auto_20181026_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='occupation_adult',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='occupation_children',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_beds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_size',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_view',
            field=models.CharField(max_length=10),
        ),
    ]
