# Generated by Django 2.1.2 on 2018-10-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0005_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
