# Generated by Django 2.1.2 on 2018-11-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0006_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_date_booked',
            field=models.ManyToManyField(blank=True, to='ownerAdmin.Date'),
        ),
    ]
