# Generated by Django 2.1.2 on 2018-11-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0009_auto_20181103_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='roomImages'),
        ),
    ]
