# Generated by Django 2.1.2 on 2018-11-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0010_auto_20181103_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.FileField(blank=True, null=True, upload_to='roomImages'),
        ),
    ]
