# Generated by Django 2.1.2 on 2018-11-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0011_auto_20181105_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='roomImages'),
        ),
    ]
