# Generated by Django 2.1.3 on 2018-11-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0012_auto_20181105_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
