# Generated by Django 2.1.3 on 2018-11-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0014_auto_20181106_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.ImageField(blank=True, default='media/roomImages/room3.jpg', null=True, upload_to='roomImages'),
        ),
    ]
