# Generated by Django 2.1.2 on 2018-12-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0016_auto_20181107_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='day',
        ),
        migrations.RemoveField(
            model_name='date',
            name='month',
        ),
        migrations.RemoveField(
            model_name='date',
            name='year',
        ),
        migrations.AddField(
            model_name='date',
            name='date',
            field=models.CharField(default='ok', max_length=20),
        ),
    ]
