# Generated by Django 2.1.3 on 2018-12-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0017_auto_20181208_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='room_view',
        ),
        migrations.AddField(
            model_name='pricing',
            name='staff_basic_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='all_inclusive_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='bed_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='breakfast_only_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='full_board_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='half_board_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='is_refundable',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
