# Generated by Django 2.1.3 on 2018-12-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0018_auto_20181209_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_features_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_beds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
