# Generated by Django 2.1.3 on 2018-12-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0019_auto_20181209_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='staff_basic_salary',
        ),
    ]
