# Generated by Django 2.1.2 on 2018-11-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('booking_year', models.CharField(max_length=4, null=True)),
                ('booking_month', models.CharField(max_length=2, null=True)),
                ('booking_day', models.CharField(max_length=2, null=True)),
                ('room', models.CharField(max_length=4, null=True)),
            ],
        ),
    ]
